language: cpp
compiler:
- gcc
install:    
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
- travis_retry wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.16.2-Linux-x86_64.tar.gz
- tar -xvf cmake-3.16.0-Linux-x86_64.tar.gz > /dev/null
- mv cmake-3.3.2-Linux-x86_64 cmake-install
- PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
- cd ${TRAVIS_BUILD_DIR}
os:
- linux
- windows
script:
- cd cpp14
- mkdir build
- cd build
- cmake ..
- cmake --build .
